package com.osu.cleanandsobertoolboxandroid;

public class Data {
    static String[] NavigationMessage = {
		"Unless otherwise indicated, the quotes and sayings in this App have no known specific author and are taken from research, the author's personal experience, training, and 12 step meetings. If anyone believes a quote or saying or any other mark or logo is not in the public domain, please contact the author immediately at the address provided. None of the information herein creates a counselor patient relationship or should substitute for any other forms of therapy. The author is not liable for any misinterpretations or any injuries claimed from the use of this App. This App provides educational information which may or may not benefit the user, and it is offered as one form of advice and not unequivocal instruction. Copyright 2014  by Clean and Sober Toolbox, Inc. All rights reserved. No part of this App shall be reproduced, stored in a retrieval system, or transmitted by any means, electronic, mechanical, photocopying, recording, or otherwise, without written permission from the publisher. No patent, trademark, copyright or other  liability is assumed with respect to the use of the information contained herein. Although every precaution has been taken in the preparation of this App, the publisher and author assume no responsibility for errors or omissions. Neither is any liability assumed for damages resulting from the use of information contained herein. The author and publisher specifically disclaim any responsibility for any liability, loss, or risk, personal or otherwise, which is incurred as a consequence, directly or indirectly, of the use and application of any of the contents of this App. This App has been registered with the United States Copyright Office.",
		"Every addict has two brains: a \"dirty brain\" and a \"clean brain.\" The \"dirty brain\" wants to drink, use, or someway act out which ultimately causes trouble. The \"clean brain\" wants to stay clean and sober and free from trouble. This app causes us to use our \"clean brain\" particularly when our \"dirty brain\" is threatening. It substitutes the threatening thought with a truthful, rescuing thought. It changes our perception of a situation from something distressful to something manageable and even positive. It does this with unprecedented ease and speed. The result of changing messages is feeling better, beating cravings, and staying sober."
	};
    
    static String[] helpMessages = {
    	"There are two ways to use this App. 1. You can enter a phrase or key words in the search engine. For example, if you are feeling like you are going to relapse because you are angry, simply type that phrase or something similar in the search engine. You can also enter the key words, relapse or anger, etc. A choice of  helpful message titles will appear. Touch a title of a message and read it. If that message doesn't help, go back to the list of titles and try another. Usually, the first message will change your thinking from addictive thinking to recovery thinking. You are encouraged to repeat to yourself the slogans found at the top of each message periodically for the rest of the day. . These slogan are commonly heard at 12 step meetings and other therapy sessions. OR 2. Touch one of the 8  questions that generally applies to your situation.  Then, on the screen that appears, touch another specific question. Finally, touch the title of a message you feel may be relevant. If that message doesn't help, go back and try another. Usually the first message will be enough to put you on the right track.You are encouraged to repeat the slogans found at the top of each message periodically for the rest of the day. Note: Sometimes you will notice that messages apply to everything in the category or they are repetitive but for a few changes which apply to a specific issue. This is intentional. Recovery depends upon constant reminders. We need to hear how a principle applies to more than one issue to stay clean and sober.",
    	"Touch a question that may apply. Quickly scroll through the list to find one.",
    	"Touch a title that speaks to you. Quickly scroll through the list to find one. After reading the message that appears, if you need more than one message to change your troubled thinking to healing thinking, touch another title for a new message."
    };
}