package com.osu.cleanandsobertoolboxandroid;

public class Data {
	static String[] Categories = {
		"Are you experiencing bad feelings like stress, anger, resentment, and fear",
		"Are you having issues going to meetings and practicing the recovery steps",
		"Are you really addicted"
	};
	
	static String[][] SubCategories = new String[][] 
		{
			{"are you in shock", "are you nervous because things seem too good", "are you upset because people don't trust or understand you"},
			{"subCategory 21", "subCategory 22", "subCategory 23"},
			{"subCategory 31", "subCategory 32", "subCategory 33"} 
		};
	
	static String[][][] Headlines = new String[][][] {
		{
			{"Don't let the bird that landed on your head build a nest", "Don't react"},
			{"Don't Think", "First Thought Wrong"},
			{"Don't Think", "First Thought Wrong"}
		},
		{
			{"Message 211", "Message 212"},
			{"Message 221", "Message 222"},
			{"Message 231", "Message 232"}
		},
		{
			{"Message 311", "Message 312"},
			{"Message 321", "Message 322"},
			{"Message 331", "Message 332"}
		}
    };

    static String[][][] Articles = new String[][][] {
    	{
    		{"\"Don’t let the bird that landed on your head make a nest.\"\n\nYou can't help it if someone throws you for a loop. No matter how much you think you can control your feelings, no matter how well adjusted you think you are, no matter how well you like the 12 steps, every now and then something will happen that will upset you. The key is to not let that bird build a nest in your head. People, places, and things cannot control your emotions. They are just emotional triggers. Remember, you make yourself feel a certain way in response to the trigger. You can also quickly change how you respond.\n\nTO DO:  What's a good way to get that bird to fly away? One way is to try to recognize your feeling, and then to try to change the bad feeling to a positive feeling. To do so, you can start by using this app. You can also ask yourself if the trigger is worth being upset about. You can also try applying the 12 steps to the feeling. First, admit that you are powerless to handle it alone. Then, turn the problem over to a Higher Power. That Higher Power may be a consultation with a sponsor, a therapist, or your God.  Maybe take an inventory and see where your own sensitivity may be contributing to the problem. If you can determine what the character sensitivity or issue is, tell someone else. If you can't determine what it is, discuss the situation with someone else. Try to find  your defect and not the defect in the person you think is causing the problem. Once you find the defect, ask God to remove it.\n\tIf the problem causes resentment, pray for the person who you think is causing the resentment.\n\tRemember to ask God that His will be done, not yours. And most importantly, try to help someone who is new to recovery. By getting out of yourself and helping another, you may be grateful that your problem is not as bad as the other person. You may gain perspective. Your attention will be re-focused.  By doing what it takes to get the bird off your head, you will avoid finding yourself saying, \"If I get drunk, I won't be able to think about it.\"",
    	     "\"Don't react, act upon.\"\n\tYou have just received an email which is insulting, inaccurate, and has caused your blood pressure to elevate such that you actually feel your chest twitching. You are in shock. You click reply. Although you think you are citing facts and being rational, you don't proofread your reply because you want to get it out of your mind and off to the offender immediately. What is the result?  A day or two (after you have completely alienated the other person), you shake your head and say \"I did it again…I wish I had never sent that email\".\n\tIt is ALWAYS advisable to wait until anger subsides before you respond to anything. When you are angry, you cannot fashion a response that fully accounts for all of the relevant factors. When angry, you cannot account for who you are responding to (is it a boss, friend, colleague, spouse). You can't exercise empathy and understanding. You can't even look at the facts objectively.\n\tEven if someone says something that provokes you, you can say \"I'll respond to that later\".\n\n\tTO DO: Wait until the anger and shock passes. When compelled to do something, don't. Be patient and follow a knee jerk reaction through to its bitter end. Before responding, consider the status of who you are responding to. Remember that we have often harmed others as a result of our addiction, so remember our amends and empathy."},
    		{"\"Don't think, Don't Drink!\"\n\n\tIt's not so much what happens to you as what you think about it. Try not to judge a person or situation as good or bad because, with time, good or bad changes. As soon as your brain gets out of control, tell yourself, \"Don't think!\" Especially, a good way to interrupt anger, worry or regret is to simply repeat to yourself, \"Don't think.\"\n\n\tTo Do: Focus on what's in front of you and remember the self message \"Don't think, don't drink.\" Once you have said that to yourself 5 times, say five times slowly to yourself: “God loves me” as you simultaneously slow and deepen your breathing.",
	         "\"First Thought Wrong\"\n\n\tIf you're nervous, don't  react.  Never trust your first thought because it usually is wrong. Always test your first thought by thinking of its consequences (good and bad) and always think of possible alternative thoughts before you act. Especially with addicts, our first thoughts tend to be harmful to ourselves and others. For example, usually our first thought when confronted with stress, anger or some other negative emotion is to lash out, withdraw, or escape by picking up our first drug of choice. We consequently regret acting upon our first thoughts. Acting upon our first thought is called a reaction.  In recovery, we learn to \"act upon\", not react, and this makes our lives easier. When our lives are easier, we don't want to act out to avoid life so we stay sober and we make better decisions.\n\n\tTo Do: Move on to the second thought. Seek counsel from others."},
    		{"\"Don't think, Don't Drink!\"\n\n\tIt's not so much what happens to you as what you think about it. Try not to judge a person or situation as good or bad because, with time, good or bad changes. As soon as your brain gets out of control, tell yourself, \"Don't think!\" Especially, a good way to interrupt anger, worry or regret is to simply repeat to yourself, \"Don't think.\"\n\n\tTo Do: Focus on what's in front of you and remember the self message \"Don't think, don't drink.\" Once you have said that to yourself 5 times, say five times slowly to yourself: \"God loves me\" as you simultaneously slow and deepen your breathing.",
	         "Article Two\n\nVinyl williamsburg non velit, master cleanse four loko banh mi. Enim kogi keytar trust fund pop-up portland gentrify. Non ea typewriter dolore deserunt Austin. Ad magna ethical kogi mixtape next level. Aliqua pork belly thundercats, ut pop-up tattooed dreamcatcher kogi accusamus photo booth irony portland. Semiotics brunch ut locavore irure, enim etsy laborum stumptown carles gentrify post-ironic cray. Butcher 3 wolf moon blog synth, vegan carles odd future."}
    	},
    	{
    		{"Article One\n\nExcepteur pour-over occaecat squid biodiesel umami gastropub, nulla laborum salvia dreamcatcher fanny pack. Ullamco culpa retro ea, trust fund excepteur eiusmod direct trade banksy nisi lo-fi cray messenger bag. Nesciunt esse carles selvage put a bird on it gluten-free, wes anderson ut trust fund twee occupy viral. Laboris small batch scenester pork belly, leggings ut farm-to-table aliquip yr nostrud iphone viral next level. Craft beer dreamcatcher pinterest truffaut ethnic, authentic brunch. Esse single-origin coffee banksy do next level tempor. Velit synth dreamcatcher, magna shoreditch in american apparel messenger bag narwhal PBR ennui farm-to-table.",
    	     "Article Two\n\nVinyl williamsburg non velit, master cleanse four loko banh mi. Enim kogi keytar trust fund pop-up portland gentrify. Non ea typewriter dolore deserunt Austin. Ad magna ethical kogi mixtape next level. Aliqua pork belly thundercats, ut pop-up tattooed dreamcatcher kogi accusamus photo booth irony portland. Semiotics brunch ut locavore irure, enim etsy laborum stumptown carles gentrify post-ironic cray. Butcher 3 wolf moon blog synth, vegan carles odd future."},
    		{"Article One\n\nExcepteur pour-over occaecat squid biodiesel umami gastropub, nulla laborum salvia dreamcatcher fanny pack. Ullamco culpa retro ea, trust fund excepteur eiusmod direct trade banksy nisi lo-fi cray messenger bag. Nesciunt esse carles selvage put a bird on it gluten-free, wes anderson ut trust fund twee occupy viral. Laboris small batch scenester pork belly, leggings ut farm-to-table aliquip yr nostrud iphone viral next level. Craft beer dreamcatcher pinterest truffaut ethnic, authentic brunch. Esse single-origin coffee banksy do next level tempor. Velit synth dreamcatcher, magna shoreditch in american apparel messenger bag narwhal PBR ennui farm-to-table.",
	         "Article Two\n\nVinyl williamsburg non velit, master cleanse four loko banh mi. Enim kogi keytar trust fund pop-up portland gentrify. Non ea typewriter dolore deserunt Austin. Ad magna ethical kogi mixtape next level. Aliqua pork belly thundercats, ut pop-up tattooed dreamcatcher kogi accusamus photo booth irony portland. Semiotics brunch ut locavore irure, enim etsy laborum stumptown carles gentrify post-ironic cray. Butcher 3 wolf moon blog synth, vegan carles odd future."},
    		{"Article One\n\nExcepteur pour-over occaecat squid biodiesel umami gastropub, nulla laborum salvia dreamcatcher fanny pack. Ullamco culpa retro ea, trust fund excepteur eiusmod direct trade banksy nisi lo-fi cray messenger bag. Nesciunt esse carles selvage put a bird on it gluten-free, wes anderson ut trust fund twee occupy viral. Laboris small batch scenester pork belly, leggings ut farm-to-table aliquip yr nostrud iphone viral next level. Craft beer dreamcatcher pinterest truffaut ethnic, authentic brunch. Esse single-origin coffee banksy do next level tempor. Velit synth dreamcatcher, magna shoreditch in american apparel messenger bag narwhal PBR ennui farm-to-table.",
	         "Article Two\n\nVinyl williamsburg non velit, master cleanse four loko banh mi. Enim kogi keytar trust fund pop-up portland gentrify. Non ea typewriter dolore deserunt Austin. Ad magna ethical kogi mixtape next level. Aliqua pork belly thundercats, ut pop-up tattooed dreamcatcher kogi accusamus photo booth irony portland. Semiotics brunch ut locavore irure, enim etsy laborum stumptown carles gentrify post-ironic cray. Butcher 3 wolf moon blog synth, vegan carles odd future."}
    	},
    	{
    		{"Article One\n\nExcepteur pour-over occaecat squid biodiesel umami gastropub, nulla laborum salvia dreamcatcher fanny pack. Ullamco culpa retro ea, trust fund excepteur eiusmod direct trade banksy nisi lo-fi cray messenger bag. Nesciunt esse carles selvage put a bird on it gluten-free, wes anderson ut trust fund twee occupy viral. Laboris small batch scenester pork belly, leggings ut farm-to-table aliquip yr nostrud iphone viral next level. Craft beer dreamcatcher pinterest truffaut ethnic, authentic brunch. Esse single-origin coffee banksy do next level tempor. Velit synth dreamcatcher, magna shoreditch in american apparel messenger bag narwhal PBR ennui farm-to-table.",
    	     "Article Two\n\nVinyl williamsburg non velit, master cleanse four loko banh mi. Enim kogi keytar trust fund pop-up portland gentrify. Non ea typewriter dolore deserunt Austin. Ad magna ethical kogi mixtape next level. Aliqua pork belly thundercats, ut pop-up tattooed dreamcatcher kogi accusamus photo booth irony portland. Semiotics brunch ut locavore irure, enim etsy laborum stumptown carles gentrify post-ironic cray. Butcher 3 wolf moon blog synth, vegan carles odd future."},
    		{"Article One\n\nExcepteur pour-over occaecat squid biodiesel umami gastropub, nulla laborum salvia dreamcatcher fanny pack. Ullamco culpa retro ea, trust fund excepteur eiusmod direct trade banksy nisi lo-fi cray messenger bag. Nesciunt esse carles selvage put a bird on it gluten-free, wes anderson ut trust fund twee occupy viral. Laboris small batch scenester pork belly, leggings ut farm-to-table aliquip yr nostrud iphone viral next level. Craft beer dreamcatcher pinterest truffaut ethnic, authentic brunch. Esse single-origin coffee banksy do next level tempor. Velit synth dreamcatcher, magna shoreditch in american apparel messenger bag narwhal PBR ennui farm-to-table.",
	         "Article Two\n\nVinyl williamsburg non velit, master cleanse four loko banh mi. Enim kogi keytar trust fund pop-up portland gentrify. Non ea typewriter dolore deserunt Austin. Ad magna ethical kogi mixtape next level. Aliqua pork belly thundercats, ut pop-up tattooed dreamcatcher kogi accusamus photo booth irony portland. Semiotics brunch ut locavore irure, enim etsy laborum stumptown carles gentrify post-ironic cray. Butcher 3 wolf moon blog synth, vegan carles odd future."},
    		{"Article One\n\nExcepteur pour-over occaecat squid biodiesel umami gastropub, nulla laborum salvia dreamcatcher fanny pack. Ullamco culpa retro ea, trust fund excepteur eiusmod direct trade banksy nisi lo-fi cray messenger bag. Nesciunt esse carles selvage put a bird on it gluten-free, wes anderson ut trust fund twee occupy viral. Laboris small batch scenester pork belly, leggings ut farm-to-table aliquip yr nostrud iphone viral next level. Craft beer dreamcatcher pinterest truffaut ethnic, authentic brunch. Esse single-origin coffee banksy do next level tempor. Velit synth dreamcatcher, magna shoreditch in american apparel messenger bag narwhal PBR ennui farm-to-table.",
	         "Article Two\n\nVinyl williamsburg non velit, master cleanse four loko banh mi. Enim kogi keytar trust fund pop-up portland gentrify. Non ea typewriter dolore deserunt Austin. Ad magna ethical kogi mixtape next level. Aliqua pork belly thundercats, ut pop-up tattooed dreamcatcher kogi accusamus photo booth irony portland. Semiotics brunch ut locavore irure, enim etsy laborum stumptown carles gentrify post-ironic cray. Butcher 3 wolf moon blog synth, vegan carles odd future."}
    	}
    };
    
    static String[] NavigationMessage = {
		"Disclaimer",
		"Psychology",
		"Are you really addicted"
	};
    /*public static void main(String args[]) {
    	System.out.println(Data.SubCategories[1][1]);
    }*/
}
